baseURL = 'http://example.org/'
defaultContentLanguage = "zh-cn"
languageCode = 'zh-CN'
languageName = "简体中文"
hasCJKLanguage = true
title = 'Kkunkka Site'
theme = 'loveit'

[author]
	name = "Kkunkka"
	email = "Kkunkka@zohomail.com"
	link = ""
