# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Setup pnpm
  # You may pin to the exact commit or the version.
  # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
      uses: pnpm/action-setup@v2.2.4
      with:
    # Version of pnpm to install
        version: latest
    # Where to store pnpm files
        #dest: # optional, default is ~/setup-pnpm
    # If specified, run `pnpm install`
        #run_install: # optional, default is null
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm i
    - run: pnpm run build --if-present
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1.0.8
      with:
    # Artifact name
        name: pages
    # Path of the directory containing the static assets.
       # path: /
    # Duration after which artifact will expire in days.
        #retention-days: 1
